import { z } from "zod"

export const BuiltinAgentNameSchema = z.enum([
  "sisyphus",
  "hephaestus",
  "prometheus",
  "oracle",
  "librarian",
  "explore",
  "multimodal-looker",
  "metis",
  "momus",
  "atlas",
  "sisyphus-junior",
  "api-lookup",
  "memory",
  "dependency-check",
  "test-writer",
  "debugger",
  "verifier",
  "ui-tester",
  "security-reviewer",
  "test-reviewer",
  "lang-reviewer",
  "architect-reviewer",
  "docs-writer",
  "git-committer",
  "web-researcher",
])

export const BuiltinSkillNameSchema = z.enum([
  "playwright",
  "dev-browser",
  "frontend",
  "git-master",
  "review-work",
  "remove-ai-slops",
  "init-deep",
  "debugging",
  "security-research",
  "security-review",
  "visual-qa",
  "team-mode",
])

export const OverridableAgentNameSchema = z.enum([
  "build",
  "plan",
  "sisyphus",
  "hephaestus",
  "sisyphus-junior",
  "OpenCode-Builder",
  "prometheus",
  "metis",
  "momus",
  "oracle",
  "librarian",
  "explore",
  "multimodal-looker",
  "atlas",
  "api-lookup",
  "memory",
  "dependency-check",
  "test-writer",
  "debugger",
  "verifier",
  "ui-tester",
  "security-reviewer",
  "test-reviewer",
  "lang-reviewer",
  "architect-reviewer",
  "docs-writer",
  "git-committer",
  "web-researcher",
])

export const AgentNameSchema = BuiltinAgentNameSchema
export type AgentName = z.infer<typeof AgentNameSchema>

export type BuiltinSkillName = z.infer<typeof BuiltinSkillNameSchema>
