import { readFileSync, writeFileSync } from "node:fs"
import { join } from "node:path"

type Entry = { readonly symbol: string; readonly minor_units?: number }
export type Currency = { readonly symbol: string; readonly decimals: number }

const ROOT = join(import.meta.dir, "..")

export function generate(): Record<string, Currency> {
  const schema = JSON.parse(readFileSync(join(ROOT, "schema/currencies.json"), "utf8")) as Record<string, Entry>
  const table: Record<string, Currency> = {}
  for (const [code, entry] of Object.entries(schema)) {
    table[code] = { symbol: entry.symbol, decimals: entry.minor_units || 2 }
  }
  const body = Object.entries(table)
    .map(([code, currency]) => `  ${code}: { symbol: ${JSON.stringify(currency.symbol)}, decimals: ${currency.decimals} },`)
    .join("\n")
  writeFileSync(join(ROOT, "src/generated/currencies.ts"), `// generated by scripts/codegen.ts\nexport const CURRENCIES: Record<string, { readonly symbol: string; readonly decimals: number }> = {\n${body}\n}\n`)
  return table
}

if (import.meta.main) generate()
